### ISSUE TITLE
AttributeError: DetectLevel instance has no attribute 'counter' 

### ISSUE THREAD

**Issue by ytssm** [ROBOTIS-GIT/turtlebot3_autorace#28]
when i finish   **AutoRace with Gazebo**,the car go to zhe Tunnel.   some wrong happened!
i can't solve them.
Please help me!   thanks a lot!!!!!!!

First
[ERROR] [1551263864.556350, 374.006000]: bad callback: <bound method DetectLevel.cbGetImage of <__main__.DetectLevel instance at 0x7fc25f365950>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/yt/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_level", line 177, in cbGetImage
    if self.counter % 3 != 0:
AttributeError: DetectLevel instance has no attribute 'counter'

Sencon
[ERROR] [1551247976.954647, 669.002000]: bad callback: <bound method ControlLane.cbFollowLane of <__main__.ControlLane instance at 0x7f628fc04d40>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/yt/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_control/nodes/control_lane", line 52, in cbFollowLane
    twist.linear.x = min(self.MAX_VEL * ((1 - abs(error) / 500) ** 2.2), 0.2)
ValueError: negative number cannot be raised to a fractional power

**Comment by kijongGil** [comment]
Hi @ytssm :)
I'm sorry for late delay.
'core_node_controller' node control each launchs. For example, when you turn on the tunnel mode. You have to turn off detect_level and control_lane node. 

Thanks,
Gilbert

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
